import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { formatCurrency, formatDate } from "@/lib/format";

export default async function QuotationPrintPage({ params }: { params: { id: string } }) {
  const supabase = createClient();
  const { data: q } = await supabase
    .from("quotations")
    .select("*, properties(name, address, city, country), guests(first_name, last_name, email, phone), organizations(name)")
    .eq("id", params.id)
    .maybeSingle();
  if (!q) notFound();

  const lines = [
    ["Accommodation", q.accommodation_amount],
    ["Dive", q.dive_amount],
    ["Transfers", q.transfer_amount],
    ["Activities", q.activities_amount],
    ["Domestic Flights", q.domestic_flight_amount],
    ["Extras", q.extras_amount],
    ["Discount", -q.discount_amount],
    ["Tax", q.tax_amount],
  ] as const;

  return (
    <div className="mx-auto max-w-2xl bg-white p-10 text-navy-900 print:p-0">
      <div className="mb-8 flex items-start justify-between">
        <div>
          <h1 className="text-xl font-bold">{(q as any).organizations?.name ?? "Pixel Core"}</h1>
          <p className="text-sm text-slate-500">{(q as any).properties?.name}</p>
        </div>
        <div className="text-right">
          <p className="text-lg font-semibold">Quotation</p>
          <p className="text-sm text-slate-500">{q.quotation_number}</p>
        </div>
      </div>

      <div className="mb-8 grid grid-cols-2 gap-6 text-sm">
        <div>
          <p className="mb-1 font-semibold text-slate-500">Prepared for</p>
          <p>{(q as any).guests ? `${(q as any).guests.first_name} ${(q as any).guests.last_name}` : "—"}</p>
          <p className="text-slate-500">{(q as any).guests?.email}</p>
        </div>
        <div>
          <p className="mb-1 font-semibold text-slate-500">Stay</p>
          <p>
            {formatDate(q.arrival_date)} → {formatDate(q.departure_date)}
          </p>
          <p className="text-slate-500">{q.meal_plan ?? "—"}</p>
        </div>
      </div>

      <table className="mb-6 w-full text-sm">
        <tbody>
          {lines.map(([label, amount]) => (
            <tr key={label} className="border-b border-slate-100">
              <td className="py-2 text-slate-600">{label}</td>
              <td className="py-2 text-right">{formatCurrency(amount, q.currency)}</td>
            </tr>
          ))}
          <tr>
            <td className="py-3 font-semibold">Total</td>
            <td className="py-3 text-right text-lg font-semibold">{formatCurrency(q.total_amount, q.currency)}</td>
          </tr>
        </tbody>
      </table>

      {q.terms && (
        <div className="mb-6 text-xs text-slate-500">
          <p className="mb-1 font-semibold">Terms</p>
          <p>{q.terms}</p>
        </div>
      )}

      <p className="text-xs text-slate-400">
        Valid until {formatDate(q.expiry_date)}. Generated by Pixel Core.
      </p>

      <div className="mt-8 rounded-lg bg-surface-alt px-4 py-3 text-xs text-slate-500 print:hidden">
        Use your browser&apos;s Print (⌘/Ctrl+P) and choose &quot;Save as PDF&quot;.
      </div>
    </div>
  );
}
